### ISSUE TITLE
Generator doesn't work?

### ISSUE THREAD

**Issue by watzon** [jeromegn/protobuf.cr#34]
The docs say to use the format `binary -I ./base/path --crystal-out ./out/dir file_or_glob` basically, but that doesn't seem to work. Having looked at the code for the binary it doesn't look like there's any option parsing being done. I tried to pipe a file in to the binary as well, but that gave me the error: `End of file reached (IO::EOFError)`.

**Comment by jeromegn** [comment]
If you'd like to fix it, I'm happy to accept a PR.

Unfortunately I don't have the time these days. Maybe @jgaskins does :)

**Comment by jgaskins** [comment]
@watzon When you say “binary”, are you talking about the `protoc` binary provided by Google or the `protoc-gen-crystal` binary provided by this shard?

**Comment by watzon** [comment]
Ahh I meant the protoc-gen-crystal bintary. Maybe the README just needs to be a little more clear, or maybe I just didn't pay enough attention.

**Comment by jgaskins** [comment]
In the README, it says to [run the `protoc` command](https://github.com/jeromegn/protobuf.cr#2-generate-pbcr-files):

> `protoc -I <.protos_basepath> --crystal_out <path_to_folder_for_protobufs> <path_to_{.proto,*.protos}>`

The `--crystal_out` flag tells `protoc` to use `protoc-gen-crystal`. Or if `protoc-gen-crystal` isn't in a directory on your path, you can use `--plugin=protoc-gen-crystal=<location-of-protoc-gen-crystal>` to specify it, as shown in the [README for my `grpc` shard](https://github.com/jgaskins/grpc#usage).

**Comment by didactic-drunk** [comment]
> Maybe the README just needs to be a little more clear

**Comment by jgaskins** [comment]
@didactic-drunk Not sure what you mean here.

**Comment by didactic-drunk** [comment]
README doesn't flow.  The current order is:
1. Installation (shards and install protoc)
2. Versioning
3. Usage: decoding & encoding
4. Usage: generating crystal protobuf messages

My first time using this I missed `Install protoc` because I thought installation meant building `protoc-gen-crystal`.

My suggestions:
* Split shard install from other instructions as those familiar with crystal may gloss over it (like I did)
* Put 1. installing protoc & 4. generating crystal protobuf under a "Building" heading next to each other so it's clear the process is 2 steps
* A note about this shard only handling protobuf v2 should be at the very top
* The other parts about the library version seem like details that mostly don't concern using the shard and probably belong at the bottom

Maybe my mistakes were unique and this is bad advice. @watzon or anyone else what did you find confusing?

**Comment by jgaskins** [comment]
> My first time using this I missed `Install protoc` because I thought installation meant building `protoc-gen-crystal`.

It's hard to know where to draw the lines because what seems clear for some may not be for others. If you want to use Protobufs in any programming language, you need to have `protoc` installed. With the perspective that installing `protoc` is step 0, sticking it up front seems like the right place.

To be fair, I agree with you 100% that it can be easy to assume that the `Installation` section only shows how to install the shard, a step we're all familiar with — I've fallen into that exact trap several times. But the issue here is that someone misread the `Usage` section and ran the wrong binary as the compiler entrypoint (as happened in this issue). I'm happy to improve the README, but I don't understand how your suggestions fix this.

> A note about this shard only handling protobuf v2 should be at the very top

This shard has supported `proto3` for 2-3 years now, but you're not the first person to get the impression that this shard is still v2-only. Do you know where that confusion is coming from so we can update it?

**Comment by didactic-drunk** [comment]
> This shard has supported `proto3` for 2-3 years now, but you're not the first person to get the impression that this shard is still v2-only. Do you know where that confusion is coming from so we can update it?

From README.md:
> This library does not follow semver conventions for versioning. It started off at v2.0.0 because it supports protobuf v2. From there, it'll increment versions based on semver, except for breaking changes, where I will not increment the major version.

Reading that seems imply version 3 will be protobuf 3 while the current version is 2.2.2 meaning no protobuf 3.

**Comment by didactic-drunk** [comment]
>  If you want to use Protobufs in any programming language, you need to have `protoc` installed. With the perspective that installing `protoc` is step 0, sticking it up front seems like the right place.

But I didn't know that.  Other projects I've worked on don't require 2 steps, possibly because someone else created a single  or 0 command installation system (chef/puppet/other).

> But the issue here is that someone misread the Usage 

Usage is in the wrong order.  The README states
1. Install protoc
2. Decoding and Encoding Messages <-- Swap
3. Install the protoc plugin <-- Swap

The order should be:
1. Thinks you do once (Installation)
2. Things you do once or maybe on upgrade (I suggest calling it Building or Building the crystal protoc plugin)
3. Things you do daily (Usage)

> Protobuf provides the protoc executable to encode, decode and generate language-specific protobuf messages via plugins.

I think this note belongs next to building the plugin or installation so newcomers to protobuf understand what they're building.

**Comment by jgaskins** [comment]
> > If you want to use Protobufs in any programming language, you need to have `protoc` installed. With the perspective that installing `protoc` is step 0, sticking it up front seems like the right place.
> 
> But I didn't know that. Other projects I've worked on don't require 2 steps, possibly because someone else created a single or 0 command installation system (chef/puppet/other).

There are plenty of resources available for that — not just Google's own documentation, but also blog posts, screencasts, and even conference talks. That you used bespoke tooling on top of `protoc` in non-Crystal projects doesn't make it the responsibility of a `protoc` plugin to help you understand the concepts that that bespoke tooling abstracted.

I don't mind trying to make documentation easier to consume, but Protobufs are pretty complex and a README is intended to be a quickstart, not a replacement for existing ecosystem documentation. We have to assume _some_ understanding.

> Usage is in the wrong order.

> The order should be

It's fine to voice your opinions or offer suggestions for how something would be easier to follow for you personally, but dictating like this won't get you the responses you want, especially given the way you joined this conversation. If you have specific suggestions, a pull request would be a lot more useful, actionable, and respectful of a maintainer's time.

**Comment by jgaskins** [comment]
I'm going to go ahead and close this issue since we've strayed off the topic and the generator does work.
