### ISSUE TITLE
Problems decoding

### ISSUE THREAD

**Issue by lancecarlson** [jeromegn/protobuf.cr#50]
I'm having a lot of trouble decoding a payload. I figured out that I need to rewind the io from looking at the specs so that I wouldn't get the dreaded Nil to Int32 failed error, but now I get this:

Unhandled exception: End of file reached (IO::EOFError)
  from /opt/homebrew/Cellar/crystal/1.6.2/share/crystal/src/io.cr:523:27 in 'read_fully'
  from /opt/homebrew/Cellar/crystal/1.6.2/share/crystal/src/io/byte_format.cr:123:3 in 'decode'
  from /opt/homebrew/Cellar/crystal/1.6.2/share/crystal/src/int.cr:763:5 in 'from_io'
  from /opt/homebrew/Cellar/crystal/1.6.2/share/crystal/src/io.cr:916:5 in 'read_bytes'
  from lib/protobuf/src/protobuf/buffer.cr:66:7 in 'read_fixed64'
  from lib/protobuf/src/protobuf/buffer.cr:9:19 in 'skip'

I know it can be hard to diagnose without the binary data so let me know what you need to help diagnose this issue

Here is a secret gist with more details:

https://gist.github.com/lancecarlson/fa97b7727d77e10a79c9c99d753959ad

**Comment by jgaskins** [comment]
Hmm, it seems to work okay for the input you provided. Added a comment to your gist so your data won't be persisted to this issue.

Skipping the size prefix on your WebSocket messages can also be done a bit more simply (since this library doesn't need or use it), by using [`Slice#+(offset : Int)`](https://crystal-lang.org/api/1.6.1/Slice.html#%2B%28offset%3AInt%29%3ASlice%28T%29-instance-method):

```crystal
ws.on_binary do |msg|
  response_login = ResponseLogin.from_protobuf(IO::Memory.new(msg + 4))
end
```

It looks like you got some bad luck on message sizes and ended up with the size prefix being interpreted as Protobuf byte markers. I don't know if the size prefix is a Protobuf thing or part of your WebSocket library, but prefixing with 4 null bytes will cause them to be skipped and interpreted just fine, while other values of those bytes will cause this error. Skipping the size prefix seems to be a good workaround for now, even if that's supposed to be valid Protobuf metadata.

Regarding your `test_io` read, I was unable to replicate that. Sanitized code:

```crystal
require "protobuf"

struct Message
  include ::Protobuf::Message

  contract_of "proto2" do
    required :a, :int32, 154467
    optional :b, :string, 153634
    repeated :c, :string, 132760
    repeated :d, :string, 132766
    optional :e, :string, 154013
    optional :f, :string, 154014
    optional :g, :string, 154712
    optional :h, :string, 154713
    optional :i, :string, 153428
    optional :j, :double, 153633
  end
end

test_io = IO::Memory.new
resp_login = Message.new(
  a: 11,
  b: "asdf",
  c: ["hello"],
  d: ["0"],
  e: "asdf",
  f: "omg",
  g: "lol",
  h: "wtf",
  i: "bbq",
  j: 60
)
resp_login.to_protobuf(test_io)
pp Message.from_protobuf(test_io.rewind)
# Message(
#  @a=11,
#  @b="asdf",
#  @c=["hello"],
#  @d=["0"],
#  @e="asdf",
#  @f="omg",
#  @g="lol",
#  @h="wtf",
#  @i="bbq",
#  @j=60.0)
```

**Comment by lancecarlson** [comment]
@jgaskins OMG! Thank you!! This worked like a CHARM:

```
response_login = ResponseLogin.from_protobuf(IO::Memory.new(msg + 4))
```
